version: '3.8'

services:
  webapp:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./webapp:/usr/share/nginx/html
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
