apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: front-end
spec:
  selector:
    matchLabels:
      app: front-end
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
       - name: nginx
         image: nginx:latest
         ports:
         - containerPort: 80