apiVersion: v1
kind: Pod
metadata:
  name: gitlab-runner
  labels:
    name: gitlab-runner
spec:
  containers:
  - name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2048Mi"
        cpu: "500m"