apiVersion: v1
kind: Pod
metadata:
  name: gitlab-runner
  labels:
    name: gitlab-runner
spec:
  containers:
  - name: gitlab-runner
    image: gitlab/gitlab-runner
    command: [apt-get update && apt-get upgrade -y]