---
apiVersion: v1
kind: Pod
metadata:
  name: gitlab-ce
  labels:
    name: gitlab-ce
spec:
  containers:
  - name: gitlab-ce
    image: gitlab/gitlab-ce
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "2048Mi"
        cpu: "500m"