version: "3.9"
services:
  gitlab-ce:
    image: gitlab/gitlab-ce
    container_name: gitlab-ce
    working_dir: /etc/gitlab
    ports:
      - 8080:80
  git-runner-1:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner-1
    working_dir: /etc/gitlab-runner
  git-runner-2:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner-2
    working_dir: /etc/gitlab-runner