version: "3.9"
services:
  gitlab-ce:
    image: gitlab/gitlab-ce
    container_name: gitlab-ce
    working_dir: /etc/gitlab
    ports:
      - 8080:80
  git-runner:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner
  srv_prog_redes:
    image: denirow/prog-redes:latest
    container_name: prog-redes
    ports:
      - 8081:80